- wazimap_ng/datasets/admin.py
- wazimap_ng/datasets/hooks.py
- wazimap_ng/datasets/tasks.py
- wazimap_ng/datasets/templates/admin/datasets_delete_confirmation.html
- wazimap_ng/datasets/templates/admin/datasets_delete_selected_confirmation.html
* Change view template and excluded related data
* Base admin model class to make changes dynamic
* Added custom action for delete_selected
* Run delete task in background
* Show notification and info messages before and after deleting data
Our delete pages were taking time because they were loading related data.
I have overwritten delete view as this is the only way we had control over related data fetch.
Right now i am showing count related data that will be deleted with object, We can remove this too if page is still slow. 
It worked fine for me and I tested for around 2M+
> Task 8 Overwrite delete view for django admin Indicator and Dataset admin

- wazimap_ng/datasets/admin.py
Got issue while i was testing for a bug.
Issue: 
Universe query in admin panel for Indicator admin was throwing error if groups does not exits.
Solution:
Send `Universe.objects.none` In case where dataset doesn't have any groups
Traceback:
> Fixed breaking universe query in case of missing groups for dataset

- wazimap_ng/config/common.py
- wazimap_ng/config/local.py
- wazimap_ng/config/production.py
Only solution I was able to found for this issue is to raise retry time as docs suggested.
Conditions of the bug:
There is 2 type of configs in Django Q 
* Retry
* Timeout
Timeout set to None by default so task will never be timed out.
If we do not set Time out and task passes the retry time, We get current behaviour that we are getting in app. (Multiple Datasets)
If we set timeout than it will not create multiple datasets as process exceeding timeout values will be dropped but will be restarted again after reaching retry value.
So process will run in loop. Like this :
> Increase retry time of Django Q so dataset queries are not duplicated

- wazimap_ng/datasets/admin/dataset_admin.py
- wazimap_ng/datasets/admin/profile_indicator_admin.py
- wazimap_ng/datasets/admin/views/variable_inlines_change.py
- wazimap_ng/datasets/static/js/sortable-widget.js
- wazimap_ng/datasets/widgets.py
@adieyal Please review.
I was not able to find any ideal solution as this issue is bit tricky.
Also did not wanted to change field type.
So solution that I implemented is :
for GET : Send list of subindicators directly to widget rather than using string and splitting by `,`.
using string and split by `,` is still there as fallback option.
for POST : If there is comma in between subindicator string. Replace it by `%2c` as when we decode it in python it will become `,` and it's unique enough.
There wasn't any other way because we are using Array field and it automatically splits string by `,`.
> Fixed issue for comma breaking subindicator sortable widget

- wazimap_ng/config/common.py
Making the DSN configurable makes it easy to distinguish messages
from prod, staging, etc
> Disable sentry by default, enable when provided a DSN.

- .codeclimate.yml
Use codeclimate for static analysis. but it should be included gradually. so we run duplication checks first
exclude the migrations folder, we don't need to check migrations. 
CodeClimate will only comment on PRs for now but will eventually be changed to inform the status (failed, pass).
https://trello.com/c/wEP9HDto/460-code-quality-checks-on-pr-diffs
> feat: add codeclimate checks

- wazimap_ng/points/views.py
@adieyal @milafrerichs Please review
There was duplicate code of get_locations and point views to filter by geography.
I have removed code from views and passed geography_code as argument to get_locations function.
All tests are passing on my local machine
> Removed duplicate code in filtering locations via geography

- wazimap_ng/points/admin/coordinate_file_admin.py
- wazimap_ng/points/dataloader.py
@adieyal @milafrerichs Please review.
It's a small bug fix for showing errors while uploading points csv.
changelog:
* Line number was not accurate for created log file
* Custom error message template was not visible in admin panel.
So our current prod server will show this for errors:
After this change is merged we will see errors like :
It will be good if we can get it merged and deployed today as jen is having difficulty in checking issues for failed points upload
> Show errors and error log file link for points upload

- tests/points/factories.py
- tests/points/test_views.py
- wazimap_ng/config/test.py
- wazimap_ng/points/views.py
@milafrerichs Please review
I was writing test for PR: https://github.com/OpenUpSA/wazimap-ng/pull/117 when I saw that you have already created point factories. So I have extended that branch to include tests and fixes for PR mentioned above.
I found couple of more issues/bugs in points location views so I have written tests for each condition and fixed bugs accordingly.
PS: I have still not closed PR: https://github.com/OpenUpSA/wazimap-ng/pull/117. Will do according to your review on this PR
https://trello.com/c/lLztLvzW/474-bug-point-download-is-broken-does-nothing#comment-5f689e697b2ed369946bb6c9
* url `api/v1/profile/<int:profile_id>/points/category/<int:profile_category_id>/geography/<str:geography_code>/points/` should not throw 404.
* Added tests for points location view
* Removed …
> Added Unit tests for points location view & fixed breaking code accordingly

- wazimap_ng/datasets/admin/dataset_file_admin.py
xlsx file was downloaded with a csv extension and it was throwing warning when opened in excel.
Fixed it by making extension dynamic
https://github.com/OpenUpSA/wazimap-ng/issues/125
upload a xlsx file in dataset upload.
Check dataset file and there should be a download link for document.
This downloaded document should not show warning for opening file in excel.
> Fix file extension for uploaded dataset file #125

- wazimap_ng/datasets/admin/dataset_file_admin.py
- wazimap_ng/datasets/dataloader.py
- wazimap_ng/datasets/tasks/process_uploaded_file.py
- wazimap_ng/datasets/templates/custom/variable_task_errors.html
- wazimap_ng/general/services/csv_helpers.py
- wazimap_ng/points/admin/coordinate_file_admin.py
- wazimap_ng/points/dataloader.py
- wazimap_ng/points/tasks.py
Added Incorrect csv log rows with error logs of csv upload.
Changed ways for logging errors in csv uploads
Point uploads will not fail if there are errors in uploaded csv
https://github.com/OpenUpSA/wazimap-ng/pull/113#issuecomment-700279710
Get a dataset file or coordinate file with errors.
After upload we should get option to download error log and incorrect csv rows in file admin.
* Made a common function to log upload errors
* Added incorrect csv rows log
* Changed dataloader, admin, upload task , error templates accordingly
> Add more info about error logs in csv uploads

- tests/datasets/factories.py
- tests/profile/test_views.py
- tests/test_cache.py
- wazimap_ng/cache.py
There were couple of issues :
* Duplicate function name for updating profile cache when profile indicator is ssaved.
* Added signals for cache update in case of geography update or subindicators group update
* Changed how dataset factory works to include profile subfactory and getting hierarchy from profile rather than creating new factory for  hierarchy
* All tests are passing but I recommend to make profile required on DB level so we are forced to add required data in tests when using factories.
#124
> Cache does not currently invalidate with change to group or subindicators #124

- tests/datasets/factories.py
- tests/profile/factories.py
- tests/profile/serializers/test_indicator_data_serializer.py
- tests/profile/test_views.py
- wazimap_ng/profile/serializers/indicator_data_serializer.py
ProfileIndicator ordering stopped working a while back - the PR fixes the serializer to ensure that data is returned in the correct order
None
Create two profile indicators. Set their order in the admin suite - check that they appear correctly in the frontend
Added tests and an order by clause in the query filter
- []  💢 edge cases in tests were considered
- [X ]  ✅ ran tests locally & are passing
> Fixed Profile Indicator Ordering

- tests/datasets/factories.py
- tests/datasets/tasks/test_process_uploaded_file.py
- wazimap_ng/datasets/tasks/process_uploaded_file.py
Using the django storage backend mechanism instead of filesystem reads when files are uploaded.
Change your storage backend from filesystem to something else such as s3 - upload a new dataset file.
> Fixed file upload file encoding

- wazimap_ng/profile/admin/admins/profile_indicator_admin.py
- wazimap_ng/profile/admin/forms/profile_indicator_form.py
Changed widget of subindicators in profile indicator admin to JsonEditor widget.
Now it looks like this: 
Update: Removed the field form admin view after review
#150 
Visit to profile indicator admin page and check subindicators section not present
Removed clean subindicator method
Removed field from admin view
> Removed subindicator field from profile indicator admin view #150

- tests/test_cache.py
- wazimap_ng/cache.py
Invalidate cache for profile when linked geography hierarchy is updated.
#139 
save geography hierarchy from admin panel and api should load hierarchy changes.
I checked if dev server logs updated.
* Added invalidate cache signal for geography hierarchy in cache.py
* Added test for change above
> Profile cache invalidation when linked geography hierarchies are updated #139

- wazimap_ng/general/admin/filters.py
This PR corrects the bug that occurs when you try to filter profile collections in the admin panel by a theme.
```bash
FieldError: Cannot resolve keyword 'profilecategory' into field. Choices are: category, category_id, created, description, icon, id, label, profile, profile_id, theme, theme_id, updated
(16 additional frame(s) were not displayed)
...
File "django/db/models/sql/query.py", line 1290, in add_q
clause, _ = self._add_q(q_object, self.used_aliases)
File "django/db/models/sql/query.py", line 1318, in _add_q
split_subq=split_subq, simple_col=simple_col,
File "django/db/models/sql/query.py", line 1190, in build_filter
lookups, parts, reffed_expression = self.solve_lookup_type(arg)
File "django/db/models/sql/query.py", line 1049, in solve_lookup_type
_, field, _, lookup_parts = …
```
> Correct bug for filtering profile categories by theme

- wazimap_ng/datasets/management/commands/load_dataset.py
It is useful to be able to script bulk uploads of datasets. Created a management command that uses the existing mechanisms for upload.
None
./manage.py "Youth Explorer" my_new_dataset /path/to/test/file.csv
file.csv should have the usual columns, i.e. Geography,Group1,Group2,...,Group N, Count
New management command.
- [X ]  🎱 no magic numbers
- [X ]  ✅ ran tests locally & are passing
> Added a management command to load datasets from the command line

- tests/datasets/tasks/test_process_uploaded_file.py
- wazimap_ng/datasets/tasks/process_uploaded_file.py
work done in #133
When you upload a dataset it should work even if there is a space at the end of the beginning of the header name. 
#151 
change the header of one of your test files to include a space. upload the file it should work regardless of the space.
* strip spaced from column headers, not only lowercase them
> fix: space in dataset upload file header names is allowed

- wazimap_ng/profile/admin/admins/profile_indicator_admin.py
Sorted Variables FK to sort by specific text `Dataset name -> Variable name`
#182 
Go to profile indicator admin page and checkout the variables drop down
Data should be sorted according to key `Dataset name -> Variable name`
Added formfield_for_foreignkey method in profile indicator admin file
> Sort variables fk in profile indicator admin #182

- tests/profile/test_views.py
- wazimap_ng/profile/views.py
The previous error message given when the wm-hostname was missing did not provide much information
N/A
http://localhost:8000/api/v1/profile_by_url/?format=json
should return a 404 with a friendlier message
- []  🔖 issue linked
- []  📖 changelog filled out
- []  black was run locally (as part of the pre-commit hook)
> Improved the 404 not found error message on profile-by-url

- wazimap_ng/datasets/admin/dataset_file_admin.py
- wazimap_ng/points/admin/coordinate_file_admin.py
I thought it's safer to use [os.path's splittext()](https://docs.python.org/3/library/os.path.html#os.path.splitext) for extracting file extensions. So, I changed the code for that. Then, I changed CoordinateFile's `get_document()` method which was extracting all files with `.csv` extension. 
Yet, I'm still suspecting that this issue might be because of the frontend side.
**Note:** I opened a PR in `wazimap-ng-ui`, which should solve this issue: https://github.com/OpenUpSA/wazimap-ng-ui/pull/170. But this PR is needed because it has some changes for coordinate files.
#125
> Update get_document() methods to extract files with correct extensions

- .gitignore
- wazimap_ng/general/static/js/profile-indicator-admin.js
- wazimap_ng/profile/admin/admins/profile_indicator_admin.py
- wazimap_ng/profile/admin/forms/profile_indicator_form.py
- wazimap_ng/profile/views.py
- wazimap_ng/urls.py
When creating a new ProfileIndicator, the subcategory dropdown does not filter options related to the selected profile - currently, subcategories from all profiles are display
https://github.com/OpenUpSA/wazimap-ng/issues/157
Pre-conditions:
- different profiles available
- multiple subcategories assigned to different profiles (through categories)
To test:
1. Open "Add profile indicator" page (http://localhost:8000/admin/profile/profileindicator/add/)
2. Select different profiles from the dropdown list
3. Check available subcategories for each profile
1. New endpoint to get the list of all subcategories related to specific profile - `/api/v1/profiles/{id}/subcategories/`
2. `profile-indicator-admin.js` file with logic to fetch subcategories on profile select
> profile indicator subcategory dropdown filtering

- wazimap_ng/points/services/locations.py
There were more colleges showing up in Steve Tshwete than there were in the database. This was found while looking at the facilities export which uses `get_locations` to get the data from the database. 
While exporting the data and importing it into QGIS it was verified that the actual data in the database was correct. 
**Problem:**
The `get_location` function uses  `contained` which uses `queryset.filter(coordinates__contained=boundary.geom)` to find all the `Locations` that are inside that geography that is passed into via a code. In our case `MP313` but `x__contained=geometry` uses the bounding box of the geometry and there were more Locations inside that bounding box 
**Solution**
using `within` makes sure that the points need to be within the actual geometry not just the bounding …
> fix: Locations/Facilities for selected geometry are correctly querried

- wazimap_ng/config/common.py
I want to get a better look inside some of the queries we run and that
are very slow, the best way to do it is on production/staging to get a
more closer look at the reality.
adding the tracing to 10% as other projects from OpenUp have done before
also adding the environment for the BE so that we can distinguish
between staging and production not using the release method (they should
be used for actual releases)
`SENTRY_PERF_SAMPLE_RATE` as env variable 
using `SERVER_INSTANCE` for sentry environments.
> Enable tracing in sentry

- tests/profile/serializers/test_indicator_data_serializer.py
- wazimap_ng/profile/serializers/indicator_data_serializer.py
When two profile_indicators from different profiles used the same
indicator, get_indicator_data returned them both. This fix explicitly
sets the correct profile.
#176 
This is difficult to test since the code causing the problem is an inner function. Hopefully the unit test serves as sufficient documentation
Fixed get_indicator_data function to only return indicator_data from a given profile
> Fixed incorrect data returned fomr get_indicator_data

- tests/points/test_views.py
- wazimap_ng/points/views.py
- wazimap_ng/urls.py
Added new endpoint for getting for points for geography
#224 
Go to new api endpoint : `api/v1/profile/<int:profile_id>/points/category/<int:profile_category_id>/points/`
* Added url in urls.py
* Added new view in points : GeoLocationList
* Added test for GeoLocationList in point view tests
* New class in point views named : GeoLocationList
* Added a new url in urls.py
* Added a test in point test_views file
> Added new endpoint for getting all points for geography #224

- tests/profile/admin/test_profile_indicator_admin.py
- tests/profile/factories.py
- wazimap_ng/profile/admin/admins/profile_indicator_admin.py
- wazimap_ng/profile/admin/forms/profile_indicator_form.py
the subcategory can now be changed again, removing the code from the
form and adding the same code that profilekeymetrics uses for the same
fxied the problem where the subcategory was not shown correctly and
therefore could not be saved
added tests for making sure the subindicator shows up when a profile
indicator is set
not super happy with the test, but works for now. 
Go to a ProfileIndicator and try to change the subcategory. It should work again and you can save it.
> fix: changing a subcategory for profile indicator

- tests/datasets/test_dataloader.py
- wazimap_ng/datasets/dataloader.py
Duplicate subindicator groups when dataset is updated.
#193 
Create a new dataset.
Reupload same file on same dataset.
Previously re uploading file with same groups created a duplicate subindicator group.
Now it should be fixed and subindicator list should be updated according to new upload
* Changed `create_groups` in `datasets/dataloader.py`
* Added tests in `datasets/test_dataloader`
> Fixed issue with duplicate subindicator groups when dataset is re-uploaded

- tests/general/test_views.py
- wazimap_ng/points/views.py
Refactor serialisers so we can use same serializer in:
* Detail_view
* Pc view
* theme view
(Not possible to use same serializer as it does too many requests to achieve same results)
Add Order field in (Already implemented):
* Pc model
* Theme model.
Both of these fields should be orderable from admin panel using sortable2  widget.(Already implemented)
Order should also change in api according to admin list order of data.
#199 
Change order of theme and profile category in admin panel and order of themes and subthemes of all_detail api should also change.
Added sorting code in point views.py
> Fix ordering issue for themes and sub themes in all_detail api endpoint

- tests/datasets/test_dataloader.py
- wazimap_ng/datasets/dataloader.py
Removed the upper case string function for geography codes.
#249
> Fix: Removed uppercasing on Geography code 

- wazimap_ng/datasets/dataloader.py
- wazimap_ng/datasets/tasks/process_uploaded_file.py
- wazimap_ng/datasets/views.py
Added a way so we can reset dataset data in upload load data.
It's better to do this delete in loaddata because it's an atomic transaction where data is created so it will only delete data if newly uploaded is added to dataset data without any error.
#238 
Reupload same file for a dataset from postman and check if there is duplicate data in indicator data.
Second way to test is if reset is set to true than Django Q logger will have a log statement of : `Deleting previously uploaded data for this dataset`
This statement will not be printed when data is uploaded via admin.
and will also have duplicate indicator data.
Added reset key to loaddata and process_uploaded_file task so we can send reset True or False from async_task to task function.
> Added a way to reset dataset data at the time of new upload

- wazimap_ng/profile/serializers/indicator_data_serializer.py
Added `last_updated_at` in all_detail api endpoint.
#239
Change can be seen on api endpoint : `http://localhost:8000/api/v1/all_details/profile/1/geography/ZA/?format=json`
added last_updated_at field in indicator_data_serializer in profile/serializers
> Added last_updated_at in all_details api endpoint for profile indicator data

- tests/test_cache.py
- wazimap_ng/cache.py
Fixed cache for points api endpoint
#195
Visit http://localhost:8000/api/v1/profile/1/points/category/1/points/?format=json
Open location object in admin panel that exist in api endpoint above
Change data in location, save and refresh the api endpoint above and location data should change.
Delete location and refresh api endpoint.
Location should be removed from response
Changed cache.py to update profile categories linked to location category
> Fixed cache for points api endpoint

- tests/datasets/test_dataloader.py
- wazimap_ng/datasets/dataloader.py
This will only fetch/create sub-indicators for filter values from the current dataset
https://github.com/OpenUpSA/wazimap-ng-ui/issues/346
https://trello.com/c/SWt9HuT3/733-productionise-vega-and-data-branch
Upload a dataset and check if group ordering contains unexpected filter values
> Filter current dataset subindicators

- wazimap_ng/config/qcluster.py
Reprocessing 450 tasks caused hetzner1 to run out of its remaining 30GB of memory.
We need to stop memory consumption from growing beyond what we can keep free on the server.
This allows us to 
1. restart worker processes more frequently, forcing garbage collection
2. limit the number of workers running concurrently, each consuming a bunch of memory
> Constrain memory during migration

- requirements.txt
We've been getting lots of `SSL error: decryption failed or bad record mac` errors from async tasks.
This has been fixed in https://github.com/Koed00/django-q/pull/556 which is included in 1.3.6
> Update Django-Q to version that fixes the SSL errors

- tests/profile/serializers/test_metrics_serializer.py
- wazimap_ng/profile/serializers/metrics_serializer.py
Check that a subindicator data point exists before trying to use it
https://github.com/OpenUpSA/wazimap-ng/issues/287
> Check if geography indicator exists before using it

- wazimap_ng/profile/serializers/indicator_data_serializer.py
Issue was because of duplicate subindicators in the api due to multiple profile indicator using same dataset.
Trello issue : https://trello.com/c/pTYHkYFv/769-duplication-of-filter-attribute-options
visit all_detail api endpoint.
Inside groups there are subindicators.
create a new profile indicator with same dataset as in the subindicator.
Now you will see there are multiple subindicators with same name here.
> Fix issue of duplicate subindicators

- tests/profile/serializers/test_metrics_serializer.py
- wazimap_ng/profile/serializers/metrics_serializer.py
There was an issue where a geography would try to access sub-indicators that did not exist
Closes #291 
Fixed cases where the backend crashed if a geography had empty sub-indicators
> Fix: Key Metric serialiser on missing geography

- wazimap_ng/cache.py
return current date when no cache key is found
> fix: disable 1970 date when no cache key is found

- wazimap_ng/datasets/templates/admin/datasets/dataset/change_form.html
- wazimap_ng/datasets/templates/admin/datasets/indicator/change_form.html
- wazimap_ng/profile/templates/admin/profile/indicatorcategory/change_form.html
- wazimap_ng/profile/templates/admin/profile/indicatorsubcategory/change_form.html
- wazimap_ng/profile/templates/admin/profile/profile/change_form.html
- wazimap_ng/profile/templates/admin/profile/profileindicator/change_form.html
allow an admin to navigate profile resources as it's structured in the actual site.
See next comment with screenshots in reverse order
> Allow user to quickly find the subindicator group for a specific profile indicator

- wazimap_ng/points/tasks.py
Point location uploads had an issue where phone numbers were dropping the leading 0. This fix should make Pandas read the value as a string instead of an interger
https://trello.com/c/iGFR5ts9/798-phone-number-in-point-data-dropping-leading-0
Please see the Trello card on how to reproduce and test
Fixed leading zero being dropped for phone numbers of point data
> Read point data from CSV files as string values

- tests/test_cache.py
- wazimap_ng/cache.py
- wazimap_ng/points/tasks.py
If cache.get returns null this is because the cache might not have been set, then set it and also set the last_modified to 1970/1/1 again
https://trello.com/c/dNjcdqsb/789-data-mapper-api-response-cache-is-broken-est-1-day
Fixed and issue where the cache was not being set
> Fixing cache errors and CI

- requirements.txt
- wazimap_ng/config/common.py
- wazimap_ng/datasets/models/geography.py
- wazimap_ng/datasets/models/metadata.py
- wazimap_ng/points/models.py
- wazimap_ng/points/tasks.py
- wazimap_ng/profile/models.py
TinyMCE adds an editor to admin pages for HTML based WYSIWYG models. Descriptions are now converted to HTML markdown. List of descriptions changed
- Dataset metadata
- Geography hierarchy
- Profile collections(category)
- Indicator category
- Indicator subcategory
- Profile indicator
- Profile
https://trello.com/c/E9XN4wrh/803-rich-text-descriptions-as-a-user-i-would-like-to-be-able-to-click-links-in-descriptions-and-read-them-easily-so-that-i-can-more
Run the service and open an admin page with a description field e.g. profile indicators. A WYSIWYG editor should appear for the description field
WYSIWYG descriptions for data admins
> Adding a WYSIWYG editor for description fields

- wazimap_ng/profile/admin/admins/profile_admin.py
- wazimap_ng/profile/models.py
Order profiles by name so that they are easier to find
https://trello.com/c/Bscyvwko/813-order-profile-admin-list-by-profile-name-by-default-so-that-i-can-easily-find-the-profile-i-want-to-edit
View the profile list page in the admin dashboard and check whether the profiles are ordered
Admin dashboard, profiles are listed in order to make them easier to find and edit
> Order profile admin list by profile name

- wazimap_ng/datasets/admin/base_admin_model.py
- wazimap_ng/general/templates/admin/base.html
Show notification after deleting datasets.
Do not show Django success notification.
Create custom notification for deleted data.
https://trello.com/c/nh1PM1ro/869-dataadmin-is-able-to-delete-dataset-without-perms-from-list-view-of-admin-panel
> Fix notifications for dataset data delete

- wazimap_ng/datasets/admin/indicator_admin.py
Removed universe from read only fields from variable edit page
https://trello.com/c/I20RPEHD/624-it-should-be-possible-to-update-the-universe-of-a-variable-from-the-django-admin-3-hours
Go to any existing variable and see if we can add/edit universe.
Removed universe from read only in variable admin
> Removed universe from read only fields for variable admin

- tests/profile/serializers/test_highlights_serializer.py
- wazimap_ng/profile/serializers/highlights_serializer.py
Fixed issue for highlight serializer
https://trello.com/c/uzo0fj1N/783-profile-highlights-if-there-is-no-data-for-the-profile-highlight-for-a-geography-the-app-might-fail
> Fixed issue in failing highlights serializer

- tests/datasets/management/test_reprocess_indicators.py
- wazimap_ng/datasets/management/commands/reprocess_indicators.py
Added a management command to reprocess indicators
Options:
* `--variables :  pass variable ids to process`
* `--datasets : pass dataset ids to process linked variables`
* `--profiles : pass profile ids to process linked variable`
* `--user_id : pass user id to get fail task notification`
* `--rerun_failed : rerun all failed tasks for extraction-ID group which will be created when we run task`
* If no option for variable, dataset & profiles is passed script will run for all existing variables
https://trello.com/c/qj0bFZj5/778-reprocess-indicators-as-a-sysadmin-i-would-like-to-be-able-to-re-process-indicator-data-so-that-changes-to-the-data-format-can-b
run management command : `docker exec -it wazimap-ng_web_1 python3 manage.py reprocess_indicators --variables 20 21 22 28 29 40 45 46`
> Added a management command to reprocess indicators

- tests/conftest.py
- tests/general/factories.py
- tests/points/admin/test_profile_category_admin.py
- tests/points/conftest.py
- wazimap_ng/general/admin/filters.py
- wazimap_ng/general/services/custom_permissions/queryset_filters.py
- wazimap_ng/general/services/permissions.py
* Fixed bug in returning queryset for models that does not contain permission field
* Fixed issue with profile collection filters
https://trello.com/c/QOFwczgp/518-point-collection-permissions-needed-for-profile-accounts
Create a user with staff perms and assign group ProfileAdmin and any profile group from admin panel.
Login in admin and check if you can CRUD Profile Collection and Themes
> Fixed permissions issue for profile admin collection

- tests/general/test_views.py
- wazimap_ng/general/views.py
- wazimap_ng/points/views.py
- wazimap_ng/urls.py
Separated api for Themes from all_details
* Create a separate URL and View in general
* Removed themes from all_details view
New URL:
`api/v1/profile/<int:profile_id>/geography/<str:geography_code>/themes_count/`
https://wazimap.atlassian.net/browse/WNCM-79
> Separate api endpoint for fetching themes/category count

- tests/general/test_all_details2.py
- tests/general/test_all_details_without_children_indicator.py
- tests/profile/serializers/test_indicator_data_for_children.py
- tests/profile/serializers/test_indicator_data_serializer.py
- tests/profile/serializers/test_indicator_data_serializer_without_children.py
- wazimap_ng/datasets/admin/__init__.py
- wazimap_ng/general/views.py
- wazimap_ng/profile/serializers/__init__.py
- wazimap_ng/profile/serializers/indicator_data_serializer.py
- wazimap_ng/profile/serializers/indicator_data_serializer_for_children.py
- wazimap_ng/profile/serializers/indicator_data_serializer_without_children.py
- wazimap_ng/profile/serializers/profile_indicator_serializer.py
- wazimap_ng/profile/serializers/profile_serializer.py
- wazimap_ng/profile/serializers/utils.py
- wazimap_ng/urls.py
Separating Child indicators from all_details
**Key Points:**
* Not removing `all_details` yet
* Adding new api endpoint : `all_details2` -> get all indicator data for geography excpet indicator data for child geographies
* Adding new api endpoint `children-indicators`-> get indicator data for child geographies
* Added new serializers and views for new api endpoints
* Reduced code redundancies as much as possible 
**Backend test list:**
all_details2:
* Copy over all all_details test to all_details2 and every test excluding test including child_data should pass
* Copy over tests for IndicatorDataSerializer and all should pass except the ones testing for child_data
* child_data not included in all_details2 either by writing a test for view or serializer
child-indicators:
* indicator data is …
> WNCM-191 Api for separating child indicator data from all_details

- wazimap_ng/datasets/models/indicator.py
- wazimap_ng/general/static/css/variable-filter-widget.css
- wazimap_ng/general/templates/widgets/VariableFilterWidget.html
* Added profile name to indicator dropdown options
* Set a max-width for the dropdown and set the title attribute of the options
https://wazimap.atlassian.net/browse/WNCM-235
* `wazimap_ng/datasets/models/indicator.py` to add the profile name 
* `wazimap_ng/general/static/css/variable-filter-widget.css` to set the max-width of the dropdown
* `wazimap_ng/general/templates/widgets/VariableFilterWidget.html` to set the `title` attribute of the options
> WNCM-235 : adding profile name to variable filter widget & setting its max width

- tests/conftest.py
- tests/datasets/admin/test_dataset_admin.py
- wazimap_ng/datasets/admin/dataset_admin.py
- wazimap_ng/datasets/admin/forms/dataset_admin_form.py
- wazimap_ng/datasets/models/geography.py
- wazimap_ng/datasets/serializers.py
- wazimap_ng/general/static/js/dataset-admin.js
- wazimap_ng/profile/views.py
- wazimap_ng/urls.py
Make sure the user can only select the valid version for the selected profile.
* Added js file to dataset admin so version dropdown changes when user change profile
* Added new url to give versions for a specific profile
* Added new view and serializer for the version to support js file 
* Updated code in dataset admin form to:
* Update version queryset when a profile is changed or according to currently selected profile
* Added validation so user can not select a version from any other profile's hierarchy
https://wazimap.atlassian.net/browse/WNCM-269
**Initial form :**
Initial form is when you try to add a new object from the admin panel
Things to check:
* If there is only one profile:
* profile should be selected by default
* versions should be filtered according to the selected profile …
> Added validations to make sure user can only select version from valid list according to profile selected

- tests/datasets/tasks/indicator_data_extraction/test_extraction.py
- wazimap_ng/datasets/tasks/indicator_data_extraction.py
Fix issue of the server running out of memory while executing an indicator data extraction task
https://wazimap.atlassian.net/browse/WNCM-265
* Create a variable and check RAM usage for task execution
* Switch branch to this fix
* Create variable with same group & dataset and observe RAM usage
* RAM usage and task execution time should be reduced
To check memory consumption use: docker stats or htop
Updated indicator data task to use values to get specific data
removed use of bulk_create
formatted using black
> Fix out of memory issue for indicator data task execution

- tests/conftest.py
- tests/profile/admin/test_profile_indicator_admin.py
- wazimap_ng/general/static/js/profile-indicator-admin.js
- wazimap_ng/general/static/js/variable-filter-widget.js
- wazimap_ng/general/templates/widgets/VariableFilterWidget.html
- wazimap_ng/general/widgets.py
- wazimap_ng/profile/admin/forms/profile_highlight_form.py
- wazimap_ng/profile/admin/forms/profile_indicator_form.py
- wazimap_ng/profile/admin/forms/profile_key_metrics.py
- wazimap_ng/profile/admin/utils.py
changing the selected variable when profile or permission type is changed while adding/modifying profile indicators
https://wazimap.atlassian.net/browse/WNCM-325
* go to add indicator page
* select a variable
* change the selected profile / permission type
* confirm that the selected variable is `---------`
> changing the selected variable option when profile or permission type is changed

- tests/datasets/admin/test_dataset_admin.py
- tests/datasets/tasks/test_process_uploaded_file.py
- tests/datasets/test_views.py
- wazimap_ng/datasets/admin/forms/dataset_admin_form.py
- wazimap_ng/datasets/models/upload.py
- wazimap_ng/datasets/views.py
Show validation errors for an uploaded file in admin panel.
Any validation error in models save throws 500 and is not handled by admin forms.
We have added save validations to the Django admin form field and clean method
We still require it at a model level as we can also upload file from API and it is using those validations
https://wazimap.atlassian.net/browse/WNCM-240
Try to upload the file without count and check if the admin panel shows a form error while saving
* Added validations to dataset admin form
* Added tests
* Made a common method to test required headers validation
> show validations errors for uploaded file via admin panel

- tests/datasets/test_views.py
- wazimap_ng/datasets/models/upload.py
Fixed failing test for WNCM-240.
Added sort to fields so the error message contains field name in same manner
https://wazimap.atlassian.net/browse/WNCM-240
> Fixed failing tests for file upload

- tests/conftest.py
- tests/datasets/tasks/indicator_data_extraction/test_extraction.py
- wazimap_ng/datasets/models/datasetdata.py
- wazimap_ng/datasets/tasks/indicator_data_extraction.py
The universe was not working for indicator data filters.
It is the way we can filter data inside indicator data. ex : Get all Male under 20 `{"gender": "male", "age__lt": "20"}` 
Previously indicator data task expected that we pass the universe from the task but now changed the approach to check if the indicator has a universe object and if there is a universe object present add it to filters.
https://wazimap.atlassian.net/browse/WNCM-332
Add universe to indicator
save variable and wait for the task to complete
Check indicator data results to verify
Changed indicator extraction process
Fixed tests accordingly
> Fix issue of universe not working for data extraction

- requirements.txt
removed mkdocs from requirements because it is not used and it causes dependabot alerts
https://wazimap.atlassian.net/browse/WNCM-353
> removed mkdocs from requirements

- tests/datasets/models/test_indicator.py
- wazimap_ng/datasets/admin/indicator_data_admin.py
- wazimap_ng/datasets/models/indicator.py
Timeout issue was coming because we were fetching dataset data queryset and filtering out unique sub-indicators on first save of variable.
For big datasets, it was taking too much time and the admin throws timeout error.
Fixed it by replacing query to get subindicators from Subindicator Groups
https://wazimap.atlassian.net/browse/WNCM-328
Not able to reproduce in local
To test on staging server:
* Go to variable add page
* search for dataset `Language - Mainplace and Subplace`
* select language in groups
* Save
> Fix timeout issue while saving indicator for first time

- tests/points/admin/test_category_admin.py
- wazimap_ng/points/admin/forms/category_admin_form.py
- wazimap_ng/points/models.py
handling the errors that occurs when points data upload is missing required columns. assumed required columns are : 
* name
* longitude
* latitude
https://wazimap.atlassian.net/browse/WNCM-274
* navigate to admin panel
* try to create a collection by uploading a file that does not contain any of the columns above
* confirm that you get a validation error
* `tests/points/admin/test_category_admin.py` for automated tests
* `wazimap_ng/points/admin/forms/category_admin_form.py` to add the `clean` method for validations
> validating the required headers while uploading points data

- tests/profile/admin/test_profile_highlights_admin.py
- tests/profile/admin/test_profile_key_metrics_admin.py
- wazimap_ng/profile/admin/admins/profile_highlight_admin.py
- wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py
- wazimap_ng/profile/models.py
Making UI changes in profile highlight & profile key metrics 
https://wazimap.atlassian.net/browse/WNCM-348
* use https://wazimap-pr-417.herokuapp.com/admin/ to test this PR
* go to profile highlights page
* confirm that there are no section headings other than `Profile fields` and `Change reason`
* confirm that the fields are ordered correctly
- Profile
- Subcategory
- Label
- Variable stuff
* confirm that helptext is added for Profile selection
* confirm that once it is saved, Profile is readonly
* repeat these for profile key metrics page
* `wazimap_ng/profile/models.py` to add help texts
* `wazimap_ng/profile/admin/admins/profile_highlight_admin.py` & `wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py` to make UI changes
> Profile highlight & Profile key metrics UI changes

- tests/points/admin/test_location_admin.py
- wazimap_ng/points/admin/location_admin.py
In location admin we are using category name in action description
It threw error if there was a % sing in name as python treated it as format string.
Fixed by adding double % sign if % is present.
https://stackoverflow.com/questions/26393895/python-how-to-escape-s/26393941#26393941
I think it's most feasible solution as we do not want to remove % sign
https://wazimap.atlassian.net/browse/WNCM-447
* Add % sign in any collection name.
* Try to open location admin list page
* Page should open up without any problems
> Sanitize location admin action name to ignore format strings

- tests/general/views/test_consolidated_profile_view.py
- wazimap_ng/profile/serializers/indicator_data_summary_serializer.py
- wazimap_ng/profile/serializers/utils.py
Updated summary api with orders of subcategory, category and profile indicator
https://wazimap.atlassian.net/browse/WNCM-277
Request summary api endpoint and it should show order and name as new keys for every subcategory, category and profile indicator
> Updated summary api to include order and name

- tests/profile/serializers/test_indicator_data_serializer_without_children.py
- wazimap_ng/profile/serializers/indicator_data_serializer_without_children.py
passing the order property for category and subcategory
https://wazimap.atlassian.net/browse/WNCM-510
Request all details api endpoint and it should show order and name as new keys for every subcategory and category
> added order property for category and subcategory

- test_selenium/profile/admin/test_profile_indicator_admin.py
- test_selenium/test_base.py
- wazimap_ng/profile/admin/forms/profile_indicator_form.py
It was due to attribute disabled set in __init__ of form.
https://wazimap.atlassian.net/browse/WNCM-509
Go to profile indicator admin.
Save new profile indicator with enable linear scrubber option checked
After save linear scrubber option should be checked
> Fixed bug in profile indicator admin initial save

- scripts/django/web.sh
Some of the API requests are taking longer than the 300 second timeout currently configured and so they time out. Until we can shift those API requests to background tasks and better caching we can temporarily increase the timeout. This change adds a `GUNICORN_TIMEOUT` environment variable defaulting to `300`.
Only works in production by default. In dev/local you could try and run the Gunicorn server with the `GUNICORN_TIMEOUT` variable set.
> Added GUNICORN_TIMEOUT env variable to allow for configurable timeouts
