OpenUpSA/wazimap-ng

wazimap_ng/datasets/views.py

* Multi group support
* Highlights also using Indicator data and indicator groups

Task-2 updating the profile view to use indicator data objects

---

wazimap_ng/datasets/views.py

@adieyal Found Bug when count doesn't exist

Fixed bug in getting default value of count if it doesn't exist.

---

wazimap_ng/points/dataloader.py

This reverts commit 757a2ba437ad7931283740592e9b58e19119b357.

Revert "Fixed bug in assigning point location"

---

wazimap_ng/datasets/templates/admin/base.html

Make admin processing notifications persist on the screen until dismissed by a user

---

wazimap_ng/points/admin.py

Ability for admin to bulk assign points to categories form admin panel

---

wazimap_ng/datasets/dataloader.py
wazimap_ng/datasets/tasks.py
wazimap_ng/datasets/views.py
wazimap_ng/points/dataloader.py
wazimap_ng/points/tasks.py

@adieyal Please review.
I have converted whole file of datasets to lower case and added strip to make process more robust.
In points I have only converted headers because I didn't wanted to change address format and we are not using that data as keys somewhere like we are using sub indicators.
I Have also changed views that were using upper case keys like profile view and detail view.

Making upload data more robust by changing whole file in lower case

---

wazimap_ng/boundaries/serializers.py

* Added a serializer field for themes in `GeographyBoundarySerializer`
* Fetched all points of a location that are in current query area.
* Get count of theme according to fetched data. 
Format:

Included count of points per theme in the all_details API call

---

.githooks/post-checkout
.gitignore
Dockerfile
Dockerfile.tmpl
Makefile

In order to initialize hooks do:
```make init```
After that every time you switch a branch it would look into the Dockerfile.tmpl file to set a dockerfile version in following format:
```branch version```

Feature githooks

---

wazimap_ng/datasets/dataloader.py
wazimap_ng/datasets/hooks.py

* convert geo code to string before converting to uppercase when uploading data set file
* Fixed issue in showing message when process of upload fails

Fixed bug in uploading dataset files

---

wazimap_ng/datasets/tasks.py

@adieyal There is some issue on staging to read file.
So Rather than sending file location I am just fetching file and providing pandas with file buffer.

Read csv file from buffer rather than reading file from source

---

wazimap_ng/config/common.py

Django Q configuration for acknowledging unsuccessful tasks

---

wazimap_ng/datasets/models/dataset.py
wazimap_ng/datasets/models/profile.py
wazimap_ng/datasets/models/upload.py
wazimap_ng/datasets/views.py
wazimap_ng/points/models.py

* Fixed Bug in showing total count in Profile Highlight
* Changed varbose name of Indicator to variable
* Fixed issue in adding key metrics to the system
* Detailed validation erorr while uploading dataset files
* Added clean method to add validations in coordinates files upload

Fixed various bugs in Datasets and Points models

---

wazimap_ng/config/common.py
wazimap_ng/points/dataloader.py
wazimap_ng/points/tasks.py

* Fixed bug in adding adding location category
* Read csv un chunks for upload
* Add levels to data json field

Added loading Geography levels while adding Location data

---

wazimap_ng/config/common.py
wazimap_ng/config/local.py
wazimap_ng/datasets/dataloader.py
wazimap_ng/datasets/models/dataset.py
wazimap_ng/datasets/models/upload.py
wazimap_ng/datasets/tasks.py

Read dataset files in chunks to avoid memory overload

---

wazimap_ng/boundaries/models.py
wazimap_ng/boundaries/tasks.py

@adieyal Please review.
After this change we will be able to update locations data according to new geography boundaries and changes to existing one.
In models I am not detecting if any field data of boundary has changed as I was not able to find a way that user can edit boundary from admin panel and In frontend we can add a check of if data is changed.

Add/Change location levels data after saving Geography boundary object

---

wazimap_ng/datasets/tasks.py

This PR will capitalize all uploaded data.

Capitalize uploaded data values

---

wazimap_ng/datasets/models/upload.py

Fixed bug in uploading xlsx file

---

wazimap_ng/points/serializers.py

Added more info about theme, subtheme and locations in point collection serializer

---

requirements.txt
wazimap_ng/config/common.py
wazimap_ng/config/production.py
wazimap_ng/datasets/tasks.py
wazimap_ng/points/tasks.py

Added amazon s3 file storage configs for production

---

wazimap_ng/datasets/models/upload.py
wazimap_ng/points/models.py

Randomise file name for data upload

---

wazimap_ng/config/local.py

Remove AWS s3 configs from local config file

---

wazimap_ng/datasets/tasks.py
wazimap_ng/points/models.py
wazimap_ng/points/tasks.py

Drop empty columns from uploaded files while extracting data

---

wazimap_ng/cache.py

Invalidate profile cache when a Highlight is added or modified

---

wazimap_ng/datasets/admin/indicator_admin.py

While creating variable form variable admin page, Datasets were not filtered according to status of the creating Dataset data task while upload.
* Added a query to filter datasets that excludes datasets which failed to create valid Dataset Data.
* Also Fixed an issue in sorting subindicators according to new subindicator structure and change in sortable widget

Fixed bug in showing datasets in variable admin page and sorting subindicators

---

wazimap_ng/points/views.py

include point source in the main profile API call

---

wazimap_ng/general/services/custom_permissions/fk_queryset_filter.py
wazimap_ng/general/services/custom_permissions/queryset_filters.py

Fixed permission for showing public dataset

---

wazimap_ng/general/static/js/indicator-admin.js

Remove universe filter according to group selected in variable admin page

---

requirements.txt
wazimap_ng/datasets/admin/views/metadata_inline_view.py
wazimap_ng/general/admin/admin_base.py
wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py

* Added lorem text as default for description fields
* Changed profile key metric field order

Added lorem text as default for description fields

---

wazimap_ng/datasets/admin/dataset_admin.py
wazimap_ng/datasets/admin/forms/__init__.py
wazimap_ng/datasets/admin/forms/indicator_admin_form.py
wazimap_ng/datasets/admin/group_admin.py
wazimap_ng/datasets/admin/indicator_admin.py
wazimap_ng/datasets/admin/indicator_data_admin.py
wazimap_ng/general/admin/filters.py
wazimap_ng/general/services/custom_permissions/queryset_filters.py
wazimap_ng/points/admin/category_admin.py
wazimap_ng/points/admin/location_admin.py
wazimap_ng/points/admin/profilecategory_admin.py
wazimap_ng/points/admin/theme_admin.py
wazimap_ng/profile/admin/admins/indicator_category_admin.py
wazimap_ng/profile/admin/admins/indicator_subcategory_admin.py
wazimap_ng/profile/admin/admins/logo_admin.py
wazimap_ng/profile/admin/admins/profile_highlight_admin.py
wazimap_ng/profile/admin/admins/profile_indicator_admin.py
wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py

Dynamic List filters for admin list views

---

wazimap_ng/datasets/tasks/process_uploaded_file.py

Fixed bug in uploading file due to index

---

wazimap_ng/datasets/admin/indicator_admin.py
wazimap_ng/points/admin/category_admin.py
wazimap_ng/points/admin/profilecategory_admin.py
wazimap_ng/points/admin/theme_admin.py
wazimap_ng/profile/admin/admins/profile_highlight_admin.py
wazimap_ng/profile/admin/admins/profile_indicator_admin.py
wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py

Added search in django admin list views

---

wazimap_ng/general/static/js/geography_hierarchy.js

Change geography hierarchy when profile is changed

---

wazimap_ng/datasets/admin/indicator_admin.py
wazimap_ng/general/static/js/indicator-admin.js

Fixed breaking jquery after adding autocomplete to datsets

---

wazimap_ng/datasets/admin/dataset_file_admin.py
wazimap_ng/points/admin/coordinate_file_admin.py

Change uploaded dataset and point file name

---

wazimap_ng/datasets/views.py

Fixed bug in loading universe after selecting dataset

---

wazimap_ng/general/admin/filters.py

Fetch unique set of choices for filters

---

wazimap_ng/datasets/admin/dataset_admin.py
wazimap_ng/general/static/js/geography_hierarchy.js
wazimap_ng/general/static/js/variable-filter-widget.js
wazimap_ng/general/static/js/variable_subindicators.js
wazimap_ng/general/widgets.py
wazimap_ng/profile/admin/admins/profile_admin.py
wazimap_ng/profile/admin/admins/profile_highlight_admin.py
wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py

Changed Jquery file formats according django

---

wazimap_ng/datasets/admin/dataset_file_admin.py
wazimap_ng/general/admin/filters.py
wazimap_ng/general/services/custom_permissions/queryset_filters.py

Added filters for dataset file admin view and changed queryset according to user

---

wazimap_ng/datasets/admin/indicator_admin.py

Added profile filter to variable admin view and removed dataset & metadata filter

---

wazimap_ng/profile/admin/admins/profile_admin.py

Added geography hierarchy in profile display and filters

---

wazimap_ng/datasets/admin/dataset_admin.py

Exclude dataset that are in upload progress

---

wazimap_ng/general/static/js/variable_subindicators.js
wazimap_ng/profile/admin/admins/profile_key_metrics_admin.py

Fixed bug in updating subcategories on load in key metrics admin

---

wazimap_ng/points/serializers.py
wazimap_ng/points/views.py

* Fixed bug when there is no image for location
I got a bug when created new data for test removing category js.
It's coming when image in location obj is empty.

Removed category data from location api

---

requirements.txt
tests/datasets/tasks/test_process_uploaded_file.py
wazimap_ng/datasets/tasks/__init__.py
wazimap_ng/datasets/tasks/process_uploaded_file.py

The code previously incorrectly capitalized data from uploaded files. This PR removes this and adds appropriate test code
None
Upload a csv file and check to make sure that the code of your data is honoured - e.g. 
```
Geography,field1,field2,count
GEOCODE_1,f1_VALue_1,F2_value_1, 111)
GEOCODE_2,F1_value_2,f2_valUE_2, 222
```
Extracted the upload csv code from the `process_uploaded_file` function in order to make it easier to test. These changes may need to be applied to the Excel upload as well.
Added appropriate tests
- [X ]  🚀 is the code ready to be merged and go live?
- [ X]  🛠 does it work (build) locally

Fixed file uploader changing case of data

---

wazimap_ng/points/admin/profilecategory_admin.py

Sort Collection FK by name for Profile collection admin
#143 
Go to profile collection admin and check collection dropdown.
Values should be ordered by name
Added formfield_for_foreignkey method for ProfileCollection admin.

Sort fk data by name for collection list in profile collection admin #143

---

README.md

Update dev env docs

---

tests/profile/serializers/test_indicator_data_serializer.py
wazimap_ng/profile/serializers/indicator_data_serializer.py

Small refactor that was a long time in coming - merge get_indicator_data and get_children_indicator_data into a single function.
N/A
N/A

Refactored get_indicator_data to accept lists of geographies

---

tests/points/test_serializers.py
tests/profile/admin/test_profile_indicator_admin.py

did not merge the result of one into the other therefore a test broke
after both got merged into staging
also removing a test focus

fix: fix a test due to changes in two PRs

---

wazimap_ng/datasets/admin/views/metadata_inline_view.py
wazimap_ng/general/admin/admin_base.py

Change lorem ipsum text to a placeholder that makes more sense
https://trello.com/c/RAWci9sH/739-as-a-data-admin-i-do-not-want-to-accidentally-save-lorem-ipsum-as-my-description-so-that-i-dont-end-up-with-nonsense-on-my-porta

Change description placeholders

---

wazimap_ng/datasets/admin/group_admin.py

Added can aggregate field in subindicator group admin
#273

Added can aggregate boolean field in group admin #273

---

wazimap_ng/datasets/migrations/0112_auto_20210527_0541.py

Fixed failing migration due to key not found while searching for index

---

wazimap_ng/datasets/migrations/0112_auto_20210527_0541.py

Fixed issue in migration for getting sorted subindicators

Fixed bug in migration for assigning sorted list to group subindicator

---

wazimap_ng/profile/serializers/indicator_data_serializer.py

Reverts OpenUpSA/wazimap-ng#290

Revert "Fix issue of duplicate subindicators"

---

wazimap_ng/profile/serializers/indicator_data_serializer.py

Fixed issue with duplicate subindicators

Fix issue of duplicate subindicators

---

wazimap_ng/datasets/templates/admin/datasets/indicator/change_form.html
wazimap_ng/profile/templates/admin/profile/profileindicator/change_form.html

Fix change form for when creating new variable and profile indicator

---

wazimap_ng/points/views.py

Fixed locations query for accurate results
https://trello.com/c/sWyhiO66/699-fix-point-in-polygon-calculation-currently-using-contains-which-returns-points-in-the-bounding-box-rather-than-in-the-geography

Fixed locations query for accurate results

---

wazimap_ng/datasets/admin/views/metadata_inline_view.py
wazimap_ng/general/admin/admin_base.py

Removed default values from admin description textbox
https://trello.com/c/aR5Y1EB0/804-remove-the-default-descriptions-again

Removed defaults from admin description textbox

---

tests/profile/views/test_views.py

https://trello.com/c/9opGLrOh/842-tutorial-customisation-only-applies-to-some-slides

Test related to front end changes for tutorial customisation

---

wazimap_ng/datasets/admin/__init__.py

Add jsoneditor for hierarchy json field

---

wazimap_ng/config/common.py

We already have code to send emails to users when there are errors processing data. But we can't currently configure SMTP credentials to be able to send the messages. This adds those settings.
Settings variables picking data up from environment variables.

Add variables to enable task error notification emails

---

wazimap_ng/general/widgets.py

ordering variables while creating profile indicator

---

tests/profile/admin/test_profile_indicator_admin.py
wazimap_ng/general/widgets.py
wazimap_ng/profile/admin/admins/profile_indicator_admin.py
wazimap_ng/profile/models.py
wazimap_ng/urls.py

For description PR: https://github.com/OpenUpSA/wazimap-ng/pull/369

Profile indicator UI change

---

.github/workflows/test.yml
docker-compose.yml
test_selenium/test_base.py
wazimap_ng/config/test.py

Fix for breaking CI on staging

Fix for broken CI

---

docker-compose.yml
test_selenium/test_base.py

Fix breaking CI
Tag version of chrome
Added new options for chrome

Fixed breaking CI

---

requirements.txt
tests/datasets/models/test_indicator.py
wazimap_ng/datasets/admin/indicator_data_admin.py
wazimap_ng/datasets/models/indicator.py

Merging staging into master
https://wazimap.atlassian.net/browse/WNCM-328

Merging Staging into Master

---

app.json
demodata.json
heroku.yml
scripts/django/web.sh
wazimap_ng/config/common.py

Added review app configs
Tested how to connect backend review apps and frontend deploy previews
Documentation for how to create a review app from CLI : https://app.gitbook.com/o/-Ly4_0FbvQFY-m3TOzuc/s/-M3zapxOsLjq_qKRcmH8/~/changes/RvWW5LSr8ObsVVf0BkMY/testing/review-apps
https://wazimap.atlassian.net/browse/WNCM-351
Follow steps to create review app and try to connect to deploy previews

Added configs for heroku review apps

---

demodata.json

wazimap-production.netlify.app to demodata profile

---

wazimap_ng/datasets/admin/__init__.py

Removed form for now so geography edit page does not throw gate way time out
https://wazimap.atlassian.net/browse/WNCM-459

Remove treebeard admin form from geography admin page

---

test_selenium/datasets/admin/test_subindicator_group.py
tests/general/views/test_consolidated_profile_view.py

* Added selenium test for django admin sortable widget
https://wazimap.atlassian.net/browse/WNCM-500

Test for subindicator ordering in admin and summary api

---

tests/conftest.py
tests/datasets/tasks/indicator_data_extraction/test_extraction.py
tests/datasets/tasks/test_process_uploaded_file.py
tests/datasets/test_views.py

updated unit tests with negative values
https://wazimap.atlassian.net/browse/WNCM-571

Updated dataset tests to include negative values

---

wazimap_ng/settings.py

Dont retry failed tasks

---

tests/general/views/test_consolidated_profile_view.py
wazimap_ng/profile/serializers/category_serializer.py
wazimap_ng/profile/serializers/indicator_data_summary_serializer.py

Added indicator details in existing categories api
Added id in profile indicator summary api
https://wazimap.atlassian.net/browse/WNCM-611

Updated profile category api endpoint to show profile indicators

---

wazimap_ng/profile/serializers/category_serializer.py

added available filter groups and their subindicators to `categories` endpoint
https://wazimap.atlassian.net/browse/WNCM-682

adding available filter groups to categories endpoint

---

wazimap_ng/datasets/views.py

https://wazimap.atlassian.net/browse/WNCM-867

Change search type in geography search api endpoint

---

wazimap_ng/cms/admin.py

Cms contents was throwing error when tried to update data
https://wazimap.atlassian.net/browse/WNCM-859

Fixed bug in updating contentes via admin

---

wazimap_ng/settings.py

Add retry and timeout config to Q_CLUSTER to prevent parellel jobs
